### ISSUE TITLE
Shader Editor ColorFragmentNode Breaks

### ISSUE THREAD

**Issue by TheBionicsonic** [paddy-exe/GodotVisualShader-Extras#24]
### Godot version

Godot v4.1.stable.official [970459615]

### System information

Windows 10

### Issue description

When trying to multiply a Texture2D and ColorFragmentNode it only obtains what seems to be a float value? I was wondering if there is a reason for that?
![GodotVisualShaderExtrasScreenshot](https://github.com/paddy-exe/GodotVisualShader-Extras/assets/95983265/fc24d67c-597d-429f-ab09-df533917a833)

**Comment by TheBionicsonic** [comment]
I realized what I made a mistake on. Didn't multiply by a Vector3 Multiply. Sorry D;

Been loving these nodes.

**Comment by paddy-exe** [comment]
@TheBionicsonic No worries! Happy to hear that you like the addon :)
